[tool.isort]
skip = [".gitignore", "./journal_api/migrations", "venv", ".git", ".tox"]

[tool.black]
line-length = 79
target-version = ['py38', 'py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  | venv
  | .tox
  | .git
  | journal_api/migrations
)/
'''