# Generated by Django 4.0.5 on 2022-06-24 14:31
import uuid
from django.db import migrations, models
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0002_category_uuid'),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; """
            """UPDATE journal_api_category SET uuid = uuid_generate_v4()::uuid WHERE uuid IS NULL;""",
            reverse_sql=RunSQL.noop
            ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
        )
    ]
