# Generated by Django 4.0.5 on 2022-06-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0003_fill_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.IntegerField(),
        ),
    ]
