# Generated by Django 4.0.5 on 2022-06-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0005_alter_category_id_alter_category_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='category_old',
        ),
    ]
