# Generated by Django 4.0.5 on 2022-06-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0007_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_old',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_api.category'),
        ),
    ]
