# Generated by Django 4.0.5 on 2022-06-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0009_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.ForeignKey(
                default="USD",
                on_delete=django.db.models.deletion.CASCADE,
                to="journal_api.currency",
            ),
        ),
    ]
