# Generated by Django 4.0.5 on 2022-07-13 20:06

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import journal_api.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0011_alter_currency_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('W', 'Week'), ('M', 'Month'), ('C', 'Custom')], default='M', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[journal_api.core.validators.validate_positive])),
                ('custom_start_date', models.DateField(default=datetime.date.today)),
                ('custom_end_date', models.DateField(default=datetime.date.today)),
                ('notification_percent', models.DecimalField(decimal_places=0, default=Decimal('80'), max_digits=3, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='journal_api.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'type')},
            },
        ),
    ]
