# Generated by Django 4.0.5 on 2022-07-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import journal_api.core.validators


def create_limits_for_users(apps, schema_editor):
    User = apps.get_model("journal_api", "User")
    Limit = apps.get_model("journal_api", "Limit")
    objs = [Limit(owner=user) for user in User.objects.all()]
    Limit.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0011_alter_currency_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_per_week', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[journal_api.core.validators.validate_positive])),
                ('limit_per_month', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[journal_api.core.validators.validate_positive])),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='journal_api.currency')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_limits_for_users, migrations.RunPython.noop)
    ]
