# Generated by Django 4.0.5 on 2022-07-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0012_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOfExceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exceeding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_api.limit')),
            ],
            options={
                'unique_together': {('limit', 'exceeding')},
            },
        ),
    ]
